configfile: "configs/general.yaml"
configfile: "configs/aligners.yaml"
configfile: "configs/ensemble.yaml"

import os
import pathlib
import pickle
import pandas as pd
import numpy as np
from Bio import AlignIO
from ensemblify.manager import infer_manager

DATA_DIR = pathlib.Path(config["general"]["input"])
OUT_DIR  = pathlib.Path(config["general"]["output"])

TOOLS = list(config["ensemble"].keys())
THREADS = {key:val["threads"] for key,val in config["aligners"].items()}

DATASETS = os.listdir(DATA_DIR)
rule all:
    input:
        done = expand(OUT_DIR / "{dataset}" / "{tool}" / "done", dataset=DATASETS, tool=TOOLS)


# # Remove gaps from already aligned data
# rule prepare_sequences:
#     input:
#         msa = DATA_DIR / "{dataset}"
#     output:
#         sequences = OUT_DIR / "{dataset}" / "sequences.fasta"
#     params:
#         dataset = lambda wildcards: wildcards.dataset
#     run:
#         # Only process if dataset is included in sample
#         if params.dataset in datasets:
#             msa_obj = Alignment(input.msa).msa

#             with open(output.sequences, "w") as outfile:
#                 for sequence in msa_obj:
#                     outfile.write(f">{sequence.id}\n")
#                     outfile.write(str(sequence.seq).replace("-", ""))
#                     outfile.write("\n")



# # Generate and pickle ensemble models 
rule generate_ensemble:
    threads: lambda wildcards: config["aligners"][config["ensemble"][wildcards.tool]["aligner"]]["threads"]
    input:
        in_file = OUT_DIR / "{dataset}" / "sequences.fasta"
    output:
        done = OUT_DIR / "{dataset}" / "{tool}" / "done"
    log:
        log_file = OUT_DIR / "{dataset}" / "{tool}"  / "ensemble.log"
    params:
        _tool = lambda wildcards: wildcards.tool,
        _dataset = lambda wildcards: wildcards.dataset
    run:
        in_file = input.in_file
        out_dir = OUT_DIR / params._dataset / params._tool
        log_file = pathlib.Path(log.log_file)
        manager_class = infer_manager(config["ensemble"][params._tool]["aligner"])
        manager = manager_class(config, params._tool, in_file, out_dir, log_file, threads, shuffle=True)
 
        ensemble = manager.compute()
        ensemble_dir = OUT_DIR / params._dataset / "ensemble"
        os.makedirs(ensemble_dir, exist_ok=True)
        manager.save_ensemble(ensemble, ensemble_dir)
        
        # Set output flag
        open(output.done, "a").close()


# rule collect:
#     input:
#         done = expand(rules.generate_ensemble.output.done, dataset=DATASETS, tool=TOOLS)
#     output:
#         global_done = OUT_DIR / "done"
#     run:
#         # Set output flag
#         open(output.global_done, "a").close()