general:
  # # # Debugging
  # input: /hits/fast/cme/bodynems/data/test_paper/test_benchin
  # output: /hits/fast/cme/bodynems/data/test_paper/test_benchout

  # # # Standard
  # input: /hits/fast/cme/bodynems/data/paper/treebase_v1
  # output: /hits/fast/cme/bodynems/data/paper/treebase_v1

  # # # Benchmarks generation
  # input: /hits/fast/cme/bodynems/data/paper/benchmarks_in
  # output: /hits/fast/cme/bodynems/data/paper
  
  # # # Multi-source: Top Folder!
  input: /hits/fast/cme/bodynems/data/paper
  output: /hits/fast/cme/bodynems/data/paper

  # sources: ["b1", "b2"]
  # sources: ["arthropod"]
  # sources: ["bali2dna",  "bali2dnaf",  "bali3",  "ox",  "prefab4",  "sabre"]
  sources: ["formatt_homstrad", "formatt_sabmark", "bralibase_k5", "bralibase_k7", "bralibase_k15"]

  raxml: "/hits/fast/cme/bodynems/tools/raxml-ng/bin/raxml-ng"
